### ISSUE TITLE
Maven Dependency not working

### ISSUE THREAD

**Issue by vicky-tbh** [Aiven-Open/gcs-connector-for-apache-kafka#309]
Hi there, 

This is Kumar, I have been learning kafka for my final semester project and wanted to do a hands-on exercise on kafka-connect, I tried including this project into my spring boot application via maven dependency but it is not working can anyone please help me with this or is what I'm doing even right can this be used as a dependency for my spring boot application? Thank you so much for considering to reply.

**Comment by ivanyu** [comment]
Hi Kumar
This is not really supposed to be used as a Java dependency directly. You need to set up a Kafka Connect worker(s) to run this connector. Please see [here](https://kafka.apache.org/documentation/#connect) for details

**Comment by bkinzle** [comment]
Hi @ivanyu - is this request not similar to the following issue where it was decided releasing to maven made sense for some people:
https://github.com/Aiven-Open/gcs-connector-for-apache-kafka/issues/77

**Comment by ivanyu** [comment]
Hi @bkinzle 
Sorry for the inconvenience, the latest release has been published, it should be available soon.
